server:
  port: 8888
  
spring:
  profiles:
    active: native
    
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
          # configuration 찾을 곳은 이제 resources - configurations folder