server:
  port: 9010
  
  
spring:
  cloud:
    gateway:
      routes:
        #Route Mapping
      - id: loginMicroservice               #RouteIdentifier
        uri: http://localhost:9002/         #Respective microservice URL which needs to be mapped
         #Request Context Path Mapping
        predicates:
        - Path=/ecommerce/login/**          
        
        #Route Mapping - With out Filters - Version 2 Request
      - id: cartMicroservice
        uri: http://localhost:9001/
        predicates:
        - Path=/ecommerceV2/**

        
        