#spring properties
spring:
  application:
    name: schools               # Eureka Server에서 보이는 name
  config:                       # meaning config server 
    import: optional:configserver:http://localhost:8888
