eureka:
  client:
    register-with-eureka: false

server:
  port: 8222
  
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
        - id: students
          uri: http://localhost:8090
          predicates:     # redirection from Path -> uri
            - Path=/api/v1/students**
        - id: schools
          uri: http://localhost:8070
          predicates:     # redirection from Path -> uri
            - Path=/api/v1/schools**
    